"""Add connector sync enhancements and sync_runs table

Revision ID: 90f33f4c6e83
Revises: 38cec5e5f786
Create Date: 2026-01-07 21:36:20.317008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90f33f4c6e83'
down_revision: Union[str, None] = '38cec5e5f786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('documents_added', sa.Integer(), server_default='0', nullable=False),
    sa.Column('documents_updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('documents_deleted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cursor_state_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_connector_id'), 'sync_runs', ['connector_id'], unique=False)
    op.create_index(op.f('ix_sync_runs_id'), 'sync_runs', ['id'], unique=False)
    op.create_index(op.f('ix_sync_runs_status'), 'sync_runs', ['status'], unique=False)
    # Drop unique index on connector_type to allow duplicate connector types
    op.drop_index('ix_connector_definitions_connector_type', 'connector_definitions')
    op.add_column('connectors', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('connectors', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('connectors', sa.Column('cursor_state_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('connectors', 'credentials_encrypted',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.LargeBinary(),
               existing_nullable=True,
               postgresql_using='credentials_encrypted::bytea')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connectors', 'credentials_encrypted',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=True)
    op.drop_column('connectors', 'cursor_state_json')
    op.drop_column('connectors', 'last_synced_at')
    op.drop_column('connectors', 'is_active')
    # Recreate unique index on connector_type
    op.create_index('ix_connector_definitions_connector_type', 'connector_definitions', ['connector_type'], unique=True)
    op.drop_index(op.f('ix_sync_runs_status'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_id'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_connector_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    # ### end Alembic commands ###
